import Head from "next/head";
import Image from "next/image";
import Greenbg from "../public/Greenbg.svg";
import styles from "../styles/Home.module.css";
import "antd-mobile/dist/antd-mobile.css";
import { Drawer, NavBar, Button, WhiteSpace, WingBlank } from "antd-mobile";
import {
  MenuOutlined,
  ShoppingCartOutlined,
  SearchOutlined,
  BorderLeftOutlined,
} from "@ant-design/icons";
import Link from 'next/link'

export default function Club(props) {
  console.log(props, "club props");
  return (
    <div className={styles.container}>
      <Head>
        <title>Drunk Elephant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar
        style={{ backgroundColor: "#6e6e6e", alignItems: "center" }}
        icon={<MenuOutlined />}
        //   onLeftClick={onOpenChange}
        rightContent={[
          <SearchOutlined key="0" />,
          <ShoppingCartOutlined key="1" />,
        ]}
      >
        DRUNK ELEPHANT
      </NavBar>
      <article style={{ backgroundColor: "#ffffff" }}>
        <div style={{ marginBottom: "3em" }}>
          <p
            style={{
              color: "#4A4A4A",
              fontSize: "44px",
              fontFamily: "Brown",
              lineHeight: "80px",
              marginLeft: "0.5em",
            }}
          >
            JOIN THE CLUB!
          </p>
          <p
            style={{
              color: "#4A4A4A",
              fontSize: "22px",
              fontWeight: "400",
              fontFamily: "Brown",
              lineHeight: "27px",
              marginLeft: "1em",
            }}
          >
            {props.data.joinclubtext}
          </p>
          <img
            style={{ marginLeft: "1.5em" }}
            src={`http://localhost:1337${props.data.image1.url}`}
            alt="new"
          />
        </div>
        <div>
          <img
            src={`http://localhost:1337${props.data.refer2.url}`}
            alt="new"
          />
        </div>
        {/* footer starts here */}
        <div style={{ backgroundColor: "#4b4b4b" }}>
          <img
            style={{ width: "100%" }}
            // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
            src={`http://localhost:1337${props.footer.drunkelephantlogo.url}`}
            alt="new"
          />{" "}
          <div style={{ color: "white", textAlign: "center" }}>
            <p>JOIN OUR MAILING LIST</p>
            <p>WHAT CAN WE HELP YOU FIND?</p>
            <p>CONTACT</p>
            <p>OUR STORY</p>
            <p>PRESS</p>
            <p>VIDEOS</p>
            <p>STORES</p>
            <p>FAQ</p>
            <p>DELIVERY & RETURNS</p>
            <p>REVIEWS</p>
            <p>AFTERPAY</p>
            <p>ACCESSIBILITY</p>
          </div>
          <img
            style={{ width: "100%" }}
            // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
            src={`http://localhost:1337${props.footer.connectwithus.url}`}
            alt="new"
          />{" "}
        </div>

        <div style={{ width: "100%", backgroundColor: "#cd56bb" }}>
          <div
            style={{
              width: "32%",
              display: "inline-block",
              textAlign: "center",
            }}
          >
            <Link href="/">
              <a>
                <img
                  style={{ width: "100%" }}
                  // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
                  src={`http://localhost:1337${props.footer.footericon1.url}`}
                  alt="new"
                />{" "}
              </a>
            </Link>
          </div>

          <div
            style={{
              width: "32%",
              display: "inline-block",
              textAlign: "center",
            }}
          >
            <Link href="/club">
              <a>
                <img
                  style={{ width: "100%" }}
                  // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
                  src={`http://localhost:1337${props.footer.footericon2.url}`}
                  alt="new"
                />{" "}
              </a>
            </Link>
          </div>

          <div
            style={{
              width: "32%",
              display: "inline-block",
              textAlign: "center",
            }}
          >
            <Link href="/sharelove">
                <a>
            <img
              style={{ width: "100%" }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.footer.footericon3.url}`}
              alt="new"
            />{" "}
            </a>
            </Link>
          </div>
        </div>
        {/* footer ends here  */}
      </article>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch("http://localhost:1337/jointheclub");
  const data = await res.json();
  console.log(data, "join club data");

  const res4 = await fetch("http://localhost:1337/footer");
  const footer = await res4.json();

  return {
    props: { data, footer }, // will be passed to the page component as props
  };
}
