import Head from "next/head";
import Image from "next/image";
import Greenbg from "../public/Greenbg.svg";
import styles from "../styles/Home.module.css";
import "antd-mobile/dist/antd-mobile.css";
import { Drawer, NavBar, Button, WhiteSpace, WingBlank } from "antd-mobile";
import {
  MenuOutlined,
  ShoppingCartOutlined,
  SearchOutlined,
  BorderLeftOutlined,
} from "@ant-design/icons";

export default function Home(props) {
  console.log(props.mixitup);

  return (
    <div className={styles.container}>
      <Head>
        <title>Drunk Elephant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar
        style={{ backgroundColor: "#6e6e6e", alignItems: "center" }}
        icon={<MenuOutlined />}
        //   onLeftClick={onOpenChange}
        rightContent={[
          <SearchOutlined key="0" />,
          <ShoppingCartOutlined key="1" />,
        ]}
      >
        DRUNK ELEPHANT
      </NavBar>

      <article style={{ backgroundColor: "#ffffff" }}>
        {/* first section starts here */}
        <div
          style={{
            backgroundColor: "#a3d4ca !important",
            textAlign: "left",
            height: "100%",
            paddingBottom: "20px",
          }}
        >
          {/* Protini Text starts here */}
          <section>
            <p style={{ marginLeft: "3em", marginRight: "5em" }}>
              <span
                style={{
                  color: "white",
                  fontSize: "40px",
                  fontFamily: "AVENIR",
                  alignContent: "left",
                  textAlign: "left",
                }}
              >
                {props.data.intro}
              </span>
            </p>
          </section>
          {/* Protini Text ends here */}

          {/* Protini Video starts here */}
          <section>
            <div className="video-background" style={{ textAlign: "center" }}>
              <iframe
                //   width="560"
                height="375"
                src="https://www.youtube.com/embed/_jVCH2UZ1cU"
                title="YouTube video player"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
            </div>
          </section>
          {/* Protini Video ends here */}
        </div>
        {/* first section ends here */}

        {/* second section starts here */}
        <div style={{ height: "60vh", backgroundColor: "#ffffff" }}>
          <section>
            <div
              style={{
                textAlign: "left",
                height: "100%",
                paddingBottom: "20px",
              }}
            >
              <h1 style={{ marginLeft: "1em" }}>{props.proTips.text}</h1>
            </div>

            {/* youtube horizontal starts here */}
            <div className="video_wrapper">
              <iframe
                style={{ marginRight: "20px", marginLeft: "2em" }}
                width="40%"
                height="300"
                src="https://www.youtube.com/embed/_jVCH2UZ1cU"
                frameBorder="0"
                allowFullScreen
              ></iframe>
              <iframe
                width="40%"
                height="300"
                src="https://www.youtube.com/embed/_jVCH2UZ1cU"
                frameBorder="0"
                allowFullScreen
              ></iframe>
              <img
                style={{ marginLeft: "2em" }}
                // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
                src={`http://localhost:1337${props.data.image.url}`}
                alt="new"
              />{" "}
              <img
                // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
                src={`http://localhost:1337${props.data.image.url}`}
                alt="new"
              />
            </div>
            {/* ends here */}
          </section>
        </div>
        {/* second section starts here */}

        {/* third section starts here */}
        <div style={{ backgroundColor: "#e4f3fb", height: '100vh' }}>
          <img
            style={{ marginLeft: "2em" }}
            // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
            src={`http://localhost:1337${props.mixitup.mixituplogo.url}`}
            alt="new"
          />{" "}
        </div>

        {/* third section ends here */}
      </article>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch("http://localhost:1337/home");
  const data = await res.json();
  console.log(data, "server data");

  const res1 = await fetch("http://localhost:1337/protips");
  const proTips = await res1.json();

  const res2 = await fetch("http://localhost:1337/mixitup");
  const mixitup = await res2.json();
  return {
    props: { data, proTips, mixitup }, // will be passed to the page component as props
  };
}
