import Head from "next/head";
import Image from "next/image";
import Greenbg from "../public/Greenbg.svg";
import styles from "../styles/Home.module.css";
import "antd-mobile/dist/antd-mobile.css";
import { Drawer, NavBar, Button, WhiteSpace, WingBlank } from "antd-mobile";
import {
  MenuOutlined,
  ShoppingCartOutlined,
  SearchOutlined,
  BorderLeftOutlined,
} from "@ant-design/icons";

export default function Home(props) {
  console.log(props.footer);

  return (
    <div className={styles.container}>
      <Head>
        <title>Drunk Elephant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar
        style={{ backgroundColor: "#6e6e6e", alignItems: "center" }}
        icon={<MenuOutlined />}
        //   onLeftClick={onOpenChange}
        rightContent={[
          <SearchOutlined key="0" />,
          <ShoppingCartOutlined key="1" />,
        ]}
      >
        DRUNK ELEPHANT
      </NavBar>

      <article style={{ backgroundColor: "#a3d4ca" }}>
        {/* first section starts here */}
        <div
          style={{
            backgroundColor: "#a3d4ca !important",
            textAlign: "left",
            height: "100%",
            paddingBottom: "20px",
          }}
        >
          {/* Protini Text starts here */}
          <section>
            <p style={{ marginLeft: "3em", marginRight: "5em" }}>
              <span
                style={{
                  color: "white",
                  fontSize: "40px",
                  fontFamily: "AVENIR",
                  alignContent: "left",
                  textAlign: "left",
                }}
              >
                {props.data.intro}
              </span>
            </p>
          </section>
          {/* Protini Text ends here */}

          {/* Protini Video starts here */}
          <section>
            <div className="video-background" style={{ textAlign: "center" }}>
              <iframe
                //   width="560"
                height="375"
                src="https://www.youtube.com/embed/_jVCH2UZ1cU"
                title="YouTube video player"
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
            </div>
          </section>
          {/* Protini Video ends here */}
        </div>
        {/* first section ends here */}

        {/* second section starts here */}
        <div style={{ height: "60vh", backgroundColor: "#ffffff" }}>
          <section>
            <div
              style={{
                textAlign: "left",
                height: "100%",
                paddingBottom: "1px",
                paddingTop: '2em'
              }}
            >
              <h1 style={{ marginLeft: "1em" }}>{props.proTips.text}</h1>
            </div>

            {/* youtube horizontal starts here */}
            <div className="video_wrapper">
              <iframe
                style={{ marginRight: "20px", marginLeft: "2em" }}
                width="40%"
                height="300"
                src="https://www.youtube.com/embed/_jVCH2UZ1cU"
                frameBorder="0"
                allowFullScreen
              ></iframe>
              <iframe
                width="40%"
                height="300"
                src="https://www.youtube.com/embed/_jVCH2UZ1cU"
                frameBorder="0"
                allowFullScreen
              ></iframe>
              <img
                style={{ marginLeft: "2em" }}
                // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
                src={`http://localhost:1337${props.data.image.url}`}
                alt="new"
              />{" "}
              <img
                // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
                src={`http://localhost:1337${props.data.image.url}`}
                alt="new"
              />
            </div>
            {/* ends here */}
          </section>
        </div>
        {/* second section starts here */}

        {/* third section starts here */}
        <div style={{ backgroundColor: "#e4f3fb", height: "75vh" }}>
          <img
            style={{
              marginLeft: "10em",
              alignItems: "center",
              paddingTop: "25px",
            }}
            // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
            src={`http://localhost:1337${props.mixitup.mixituplogo.url}`}
            alt="new"
          />{" "}
          <section>
            <p style={{ marginLeft: "3em", marginRight: "5em" }}>
              <span
                style={{
                  color: "#FF8B6A",
                  fontSize: "18px",
                  lineHeight: "23px",
                  fontFamily: "AVENIR",
                  alignContent: "left",
                  // textAlign: "left",
                }}
              >
                {props.mixitup.sometextpara}
              </span>
            </p>
            <img
              style={{
                marginLeft: "2em",
                alignItems: "center",
                paddingTop: "25px",
              }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.mixitup.featuredsmoothieimage.url}`}
              alt="new"
            />{" "}
            <img
              style={{
                width: "-webkit-fill-available",
                alignItems: "center",
                paddingTop: "25px",
              }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.mixitup.timelogos.url}`}
              alt="new"
            />{" "}
          </section>
        </div>

        {/* third section ends here */}

        {/* fourth section starts here */}
        {/* Sunshine Smoothie Starts Here */}
        <div
          style={{
            paddingTop: "4em",
            paddingLeft: "2em",
            backgroundColor: '#ffffff'
          }}
        >
          <div className="image">
            <img
              src={`http://localhost:1337${props.smoothie.smoothieborder.url}`}
              alt="new"
            />
            <div
              className="sunshine-text"
              style={{
                position: "absolute",
                top: "229%",
                width: "100%",
                color: "black",
                fontSize: "22px",
              }}
            >
              <p style={{ marginLeft: "2em" }}>Sunshine Smoothie</p>
              <img
                style={{ marginLeft: "4em" }}
                src={`http://localhost:1337${props.smoothie.product1.url}`}
                alt="new"
              />
              <br></br>
              <img
                src={`http://localhost:1337${props.smoothie.product2.url}`}
                alt="new"
              />
              <br></br>
              <img
                style={{ marginLeft: "4em" }}
                src={`http://localhost:1337${props.smoothie.product3.url}`}
                alt="new"
              />
              <br></br>
              <img
                src={`http://localhost:1337${props.smoothie.product2.url}`}
                alt="new"
              />
              <br></br>
              <img
                style={{ marginLeft: "4em" }}
                src={`http://localhost:1337${props.smoothie.product1.url}`}
                alt="new"
              />
            </div>
          </div>

          <p
            style={{
              margin: "10% 10% 10% 10%",
              fontFamily: "brown",
              fontSize: "16px",
              fontStyle: "Bold",
              fontWeight: "700",
            }}
          >
            FOR FIRMER, BRONZY, GLOWING SKIN
          </p>
          <WingBlank style={{ paddingBottom: "30px" }}>
            <Button
              style={{
                backgroundColor: "#d59363",
                color: "#fdfaf8",
                marginLeft: "12%",
                marginRight: "19%",
              }}
            >
              SHOP THIS SMOOTHIE
            </Button>
            <WhiteSpace />
          </WingBlank>
        </div>
        {/* Sunshine Smoothie Ends Here */}
        {/* fourth section ends here */}
        {/* footer starts here */}
        <div style={{ backgroundColor: "#4b4b4b" }}>
          <img
            style={{ width: "100%" }}
            // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
            src={`http://localhost:1337${props.footer.drunkelephantlogo.url}`}
            alt="new"
          />{" "}
          <div style={{ color: "white", textAlign: "center" }}>
            <p>JOIN OUR MAILING LIST</p>
            <p>WHAT CAN WE HELP YOU FIND?</p>
            <p>CONTACT</p>
            <p>OUR STORY</p>
            <p>PRESS</p>
            <p>VIDEOS</p>
            <p>STORES</p>
            <p>FAQ</p>
            <p>DELIVERY & RETURNS</p>
            <p>REVIEWS</p>
            <p>AFTERPAY</p>
            <p>ACCESSIBILITY</p>
          </div>
          <img
            style={{ width: "100%" }}
            // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
            src={`http://localhost:1337${props.footer.connectwithus.url}`}
            alt="new"
          />{" "}
        </div>

        <div style={{ width: "100%", backgroundColor: "#cd56bb" }}>
          <div
            style={{
              width: "32%",
              display: "inline-block",
              textAlign: "center",
            }}
          >
            <img
              style={{ width: "100%" }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.footer.footericon1.url}`}
              alt="new"
            />{" "}
            {/* <img
                    src={GetStarted}
                    className="GetStarted"
                    alt="GetStarted"
                    style={{ marginBottom: "16px" }}
                  /> */}
          </div>

          <div
            style={{
              width: "32%",
              display: "inline-block",
              textAlign: "center",
            }}
          >
            {/* <Link to="/JoinClub"> */}
            <img
              style={{ width: "100%" }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.footer.footericon2.url}`}
              alt="new"
            />{" "}
            {/* </Link> */}
          </div>

          <div
            style={{
              width: "32%",
              display: "inline-block",
              textAlign: "center",
            }}
          >
            {/* <Link to="/ShareLove"> */}
            <img
              style={{ width: "100%" }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.footer.footericon3.url}`}
              alt="new"
            />{" "}
            {/* </Link> */}
          </div>
        </div>
        {/* footer ends here  */}
      </article>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch("http://localhost:1337/home");
  const data = await res.json();
  console.log(data, "server data");

  const res1 = await fetch("http://localhost:1337/protips");
  const proTips = await res1.json();

  const res2 = await fetch("http://localhost:1337/mixitup");
  const mixitup = await res2.json();

  const res3 = await fetch("http://localhost:1337/smoothie");
  const smoothie = await res3.json();

  const res4 = await fetch("http://localhost:1337/footer");
  const footer = await res4.json();

  return {
    props: { data, proTips, mixitup, smoothie, footer }, // will be passed to the page component as props
  };
}
