import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "antd-mobile/dist/antd-mobile.css";
import { Drawer, NavBar, Button, WhiteSpace, WingBlank } from "antd-mobile";
import {
  MenuOutlined,
  ShoppingCartOutlined,
  SearchOutlined,
  BorderLeftOutlined,
} from "@ant-design/icons";
import Link from "next/link";
import trendingbg from "../public/trendingbg.svg";

export default function ShareLove(props) {
  console.log(props.data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Drunk Elephant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar
        style={{ backgroundColor: "#6e6e6e", alignItems: "center" }}
        icon={<MenuOutlined />}
        //   onLeftClick={onOpenChange}
        rightContent={[
          <SearchOutlined key="0" />,
          <ShoppingCartOutlined key="1" />,
        ]}
      >
        DRUNK ELEPHANT
      </NavBar>
      <article>
        <div>
          <div style={{ marginLeft: "2em" }}>
            <h1>{props.data.headline}</h1>
            <p>{props.data.subtext}</p>
            <div className="video_wrapper">
              <iframe
                style={{ marginRight: "20px" }}
                width="40%"
                height="300"
                src="https://www.youtube.com/embed/Fhkhkmufvc4"
                frameBorder="0"
                allowFullScreen
              ></iframe>
              <iframe
                width="40%"
                height="300"
                src="https://www.youtube.com/embed/Fhkhkmufvc4"
                frameBorder="0"
                allowFullScreen
              ></iframe>
              <div className="row">
                <p
                  style={{
                    float: "left",
                    textAlign: "left",
                    width: "40%",
                    marginRight: "0,5em",
                    paddingLeft: "1em",
                  }}
                >
                  {props.data.videotext}>
                </p>
                <p style={{ float: "left", textAlign: "left", width: "40%" }}>
                  {props.data.videotext}
                </p>
              </div>
            </div>
          </div>
          <div>
            <img
              style={{ width: "100%" }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.data.image1.url}`}
              alt="new"
            />{" "}
          </div>
          <div>
            <img
              style={{ width: "100%" }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.data.shareloveimage.url}`}
              alt="new"
            />{" "}
          </div>
          {/* footer starts here */}
          {/* footer starts here */}
          <div style={{ backgroundColor: "#4b4b4b" }}>
            <img
              style={{ width: "100%" }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.footer.drunkelephantlogo.url}`}
              alt="new"
            />{" "}
            <div style={{ color: "white", textAlign: "center" }}>
              <p>JOIN OUR MAILING LIST</p>
              <p>WHAT CAN WE HELP YOU FIND?</p>
              <p>CONTACT</p>
              <p>OUR STORY</p>
              <p>PRESS</p>
              <p>VIDEOS</p>
              <p>STORES</p>
              <p>FAQ</p>
              <p>DELIVERY & RETURNS</p>
              <p>REVIEWS</p>
              <p>AFTERPAY</p>
              <p>ACCESSIBILITY</p>
            </div>
            <img
              style={{ width: "100%" }}
              // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
              src={`http://localhost:1337${props.footer.connectwithus.url}`}
              alt="new"
            />{" "}
          </div>

          <div style={{ width: "100%", backgroundColor: "#cd56bb" }}>
            <div
              style={{
                width: "32%",
                display: "inline-block",
                textAlign: "center",
              }}
            >
              <Link href="/">
                <a>
                  <img
                    style={{ width: "100%" }}
                    // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
                    src={`http://localhost:1337${props.footer.footericon1.url}`}
                    alt="new"
                  />{" "}
                </a>
              </Link>
            </div>

            <div
              style={{
                width: "32%",
                display: "inline-block",
                textAlign: "center",
              }}
            >
              <Link href="/club">
                <a>
                  <img
                    style={{ width: "100%" }}
                    // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
                    src={`http://localhost:1337${props.footer.footericon2.url}`}
                    alt="new"
                  />{" "}
                </a>
              </Link>
            </div>

            <div
              style={{
                width: "32%",
                display: "inline-block",
                textAlign: "center",
              }}
            >
              <Link href="/sharelove">
                <a>
                  <img
                    style={{ width: "100%" }}
                    // uploads/Drunk_Elephant_Logo_e75c1f076d.png",
                    src={`http://localhost:1337${props.footer.footericon3.url}`}
                    alt="new"
                  />{" "}
                </a>
              </Link>
            </div>
          </div>
          {/* footer ends here  */}
        </div>
      </article>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch("http://localhost:1337/sharelove");
  const data = await res.json();
  console.log(data, "server data");

  const res4 = await fetch("http://localhost:1337/footer");
  const footer = await res4.json();

  return {
    props: { data, footer }, // will be passed to the page component as props
  };
}
